og_heretics_poolA = Series_Simulation(OpTic, Heretics)
og_heretics_poolA %>% extract2(3)
# OG 78%, OG 3-1 (Control)
og_eg_poolA = Series_Simulation(OpTic, 'Evil Geniuses')
og_eg_poolA %>% extract2(3)
# OG 80%, OG 3-0 or 3-1 (Control)
og_denial_poolA = Series_Simulation(OpTic, Denial)
og_denial_poolA %>% extract2(3)
# OG 79%, OG 3-1 (SnD)
heretics_eg_poolA = Series_Simulation(Heretics, 'Evil Geniuses')
heretics_eg_poolA %>% extract2(3)
# Heretics 51%, Heretics 3-2 or EG 3-1 (Control winner wins series)
heretics_denial_poolA = Series_Simulation(Heretics, Denial)
heretics_denial_poolA %>% extract2(3)
# Heretics 53%, Heretics 3-1 or Denial 3-2 (Denial wins if they steal a respawn, probably Control)
eg_denial_poolA = Series_Simulation('Evil Geniuses', Denial)
eg_denial_poolA %>% extract2(3)
# 50/50, whoever wins Control wins series (EG 3-1 or Denial 3-2)