Create_Team('100 Thieves', c('Enable', 'Kenny', 'Octane', 'Preistahh', 'Slasher'))
Create_Team(Denial, c('Alex', 'Bance', 'Brack', 'Joee', 'Rated'))
Create_Team(Elevate, c('Breszy', 'MRuiz', 'Profeezy', 'Skyz', 'Wailers'))
Create_Team(Enigma6, c('Frosty', 'General', 'GodRx', 'Jetli', 'Kismet'))
Create_Team(EnVy, c('Aches', 'Decemate', 'Fero', 'Huke', 'Silly'))
Create_Team(eUnited, c('Abezy', 'Arcitys', 'Clayster', 'Prestinni', 'Simp'))
Create_Team('Evil Geniuses', c('Apathy', 'Attach', 'JKap', 'Phantomz', 'Xotic'))
Create_Team(FaZe, c('Asim', 'Cellium', 'Skrapz', 'Zer0', 'Zoomaa'))
Create_Team(Gen.G, c('Envoy', 'Havok', 'MajorManiak', 'Maux', 'Nagafen'))
Create_Team(Heretics, c('JurNii', 'Lucky', 'MethodZsick', 'Mettalz', 'Sukry'))
Create_Team(Luminosity, c('Classic', 'Formal', 'John', 'Ricky', 'Slacked'))
Create_Team(Midnight, c('Blazt', 'Lacefield', 'LlamaGod', 'Parasite', 'Saints'))
Create_Team(OpTic, c('Crimsix', 'Dashy', 'Karma', 'Scump', 'TJHaly'))
Create_Team(Reciprocity, c('Denz', 'Dylan', 'Seany', 'Wuskin', 'Zed'))
Create_Team(Splyce, c('Aqua', 'Jurd', 'Loony', 'Nolson', 'Temp'))
Create_Team(UYU, c('Mayhem', 'Methodz', 'Parzelion', 'Royalty', 'Zaptius'))

#saveRDS(Team.List, 'Objects/Team.List')
