source('Functions/Elo_Functions.R')
Player.List = readRDS('Objects/Player.List')


#### PL Week 1 - Week 4 ####
# Week 1
Series('Data/Pro League/PL - 1_rec_rr.csv', Pro_League)
Series('Data/Pro League/PL - 2_mid_og.csv', Pro_League)
Series('Data/Pro League/PL - 3_eg_mid.csv', Pro_League)
Series('Data/Pro League/PL - 4_geng_rr.csv', Pro_League)
Series('Data/Pro League/PL - 5_og_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 6_lg_rec.csv', Pro_League)
Series('Data/Pro League/PL - 7_geng_rec.csv', Pro_League)
Series('Data/Pro League/PL - 8_lg_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 9_mid_rr.csv', Pro_League)
Series('Data/Pro League/PL - 10_eg_og.csv', Pro_League)
Series('Data/Pro League/PL - 11_mid_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 12_og_rec.csv', Pro_League)
Series('Data/Pro League/PL - 13_lg_red.csv', Pro_League)
Series('Data/Pro League/PL - 14_eg_geng.csv', Pro_League)
# Week 2
Series('Data/Pro League/PL - 15_eg_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 16_geng_lg.csv', Pro_League)
Series('Data/Pro League/PL - 17_mid_rec.csv', Pro_League)
Series('Data/Pro League/PL - 18_geng_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 19_og_rr.csv', Pro_League)
Series('Data/Pro League/PL - 20_eg_lg.csv', Pro_League)
Series('Data/Pro League/PL - 21_rec_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 22_eg_rr.csv', Pro_League)
Series('Data/Pro League/PL - 23_lg_mid.csv', Pro_League)
Series('Data/Pro League/PL - 24_geng_og.csv', Pro_League)
Series('Data/Pro League/PL - 25_rr_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 26_geng_mid.csv', Pro_League)
Series('Data/Pro League/PL - 27_eg_rec.csv', Pro_League)
Series('Data/Pro League/PL - 28_lg_og.csv', Pro_League)
# Week 3
Series('Data/Pro League/PL - 29_eu_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 30_denial_e6.csv', Pro_League)
Series('Data/Pro League/PL - 31_denial_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 32_xlg_nv.csv', Pro_League)
Series('Data/Pro League/PL - 33_e6_eu.csv', Pro_League)
Series('Data/Pro League/PL - 34_100t_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 35_100t_denial.csv', Pro_League)
Series('Data/Pro League/PL - 36_e6_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 37_eu_xlg.csv', Pro_League)
Series('Data/Pro League/PL - 38_splyce_nv.csv', Pro_League)
Series('Data/Pro League/PL - 39_xlg_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 40_denial_nv.csv', Pro_League)
Series('Data/Pro League/PL - 41_e6_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 42_100t_eu.csv', Pro_League)
# Week 4
Series('Data/Pro League/PL - 43_100t_nv.csv', Pro_League)
Series('Data/Pro League/PL - 44_xlg_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 45_denial_eu.csv', Pro_League)
Series('Data/Pro League/PL - 46_100t_xlg.csv', Pro_League)
Series('Data/Pro League/PL - 47_heretics_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 48_e6_nv.csv', Pro_League)
Series('Data/Pro League/PL - 49_eu_nv.csv', Pro_League)
Series('Data/Pro League/PL - 50_e6_xlg.csv', Pro_League)
Series('Data/Pro League/PL - 51_denial_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 52_100t_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 53_denial_xlg.csv', Pro_League)
Series('Data/Pro League/PL - 54_heretics_nv.csv', Pro_League)
Series('Data/Pro League/PL - 55_100t_e6.csv', Pro_League)
Series('Data/Pro League/PL - 56_eu_splyce.csv', Pro_League)


#### Fort Worth ####
Series('Data/Fort Worth/FW - 1_e6_rr.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 2_mid_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 3_xlg_lg.csv', Fort_Worth)
#Series('Data/Fort Worth/FW - 4_100t_eg.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 5_geng_heretics.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 6_eu_nv.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 7_og_rec.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 8_denial_uyu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 9_100t_rr.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 10_xlg_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 11_e6_eg.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 12_lg_mid.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 13_og_nv.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 14_heretics_uyu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 15_eu_rec.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 16_denial_geng.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 17_lg_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 18_eg_rr.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 19_xlg_mid.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 20_100t_e6.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 21_eu_og.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 22_denial_heretics.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 23_geng_uyu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 24_rec_nv.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 25_e6_rec.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 26_geng_lg.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 27_eg_og.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 28_mid_uyu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 29_denial_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 30_xlg_heretics.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 31_100t_eu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 32_red_nv.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 33_geng_og.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 34_100t_denial.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 35_heretics_nv.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 36_rec_uyu.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 37_e6_lg.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 38_100t_heretics.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 39_rr_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 40_geng_rec.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 41_100t_e6.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 42_rec_rr.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 43_100t_rec.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 44_lg_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 45_rec_splyce.csv', Fort_Worth)
Series('Data/Fort Worth/FW - 46_lg_splyce.csv', Fort_Worth)

#### Pro League Week 5 - Week 6 ####
# Week 5
Series('Data/Pro League/PL - 57_heretics_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 58_xlg_rr.csv', Pro_League)
Series('Data/Pro League/PL - 59_lg_nv.csv', Pro_League)
Series('Data/Pro League/PL - 60_eu_eg.csv', Pro_League)
Series('Data/Pro League/PL - 61_eg_heretics.csv', Pro_League)
Series('Data/Pro League/PL - 62_eu_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 63_xlg_lg.csv', Pro_League)
Series('Data/Pro League/PL - 64_rr_nv.csv', Pro_League)
Series('Data/Pro League/PL - 65_heretics_rr.csv', Pro_League)
Series('Data/Pro League/PL - 66_xlg_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 67_eg_nv.csv', Pro_League)
Series('Data/Pro League/PL - 68_lg_eu.csv', Pro_League)
Series('Data/Pro League/PL - 69_nv_uyu.csv', Pro_League)
Series('Data/Pro League/PL - 70_eg_xlg.csv', Pro_League)
Series('Data/Pro League/PL - 71_eu_rr.csv', Pro_League)
Series('Data/Pro League/PL - 72_heretics_lg.csv', Pro_League)
Series('Data/Pro League/PL - 73_denial_geng.csv', Pro_League)
Series('Data/Pro League/PL - 74_mid_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 75_e6_og.csv', Pro_League)
Series('Data/Pro League/PL - 76_100t_rec.csv', Pro_League)
Series('Data/Pro League/PL - 77_denial_og.csv', Pro_League)
Series('Data/Pro League/PL - 78_e6_rec.csv', Pro_League)
Series('Data/Pro League/PL - 79_100t_mid.csv', Pro_League)
Series('Data/Pro League/PL - 80_geng_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 81_e6_mid.csv', Pro_League)
Series('Data/Pro League/PL - 82_denial_rec.csv', Pro_League)
Series('Data/Pro League/PL - 83_100t_geng.csv', Pro_League)
Series('Data/Pro League/PL - 84_og_splyce.csv', Pro_League)
Series('Data/Pro League/PL - 85_e6_geng.csv', Pro_League)
Series('Data/Pro League/PL - 86_denial_mid.csv', Pro_League)
Series('Data/Pro League/PL - 87_rec_splyce.csv', Pro_League)
#Series('Data/Pro League/PL - 88_og_100t.csv', Pro_League)


#### London ####
#Series('Data/London/London - 1_lg_geng.csv', London)
#Series('Data/London/London - 2_eg_faze.csv', London)
#Series('Data/London/London - 3_100t_rec.csv', London)
#Series('Data/London/London - 4_nv_eu.csv', London)
#Series('Data/London/London - 5_splyce_denial.csv', London)
Series('Data/London/London - 6_heretics_uyu.csv', London)
Series('Data/London/London - 7_elevate_mid.csv', London)
Series('Data/London/London - 8_e6_og.csv', London)
Series('Data/London/London - 9_eg_nv.csv', London)
Series('Data/London/London - 10_denial_lg.csv', London)
Series('Data/London/London - 11_geng_splyce.csv', London)
Series('Data/London/London - 12_eu_faze.csv', London)
Series('Data/London/London - 13_og_rec.csv', London)
Series('Data/London/London - 14_100t_e6.csv', London)
Series('Data/London/London - 15_elevate_heretics.csv', London)
Series('Data/London/London - 16_mid_uyu.csv', London)
Series('Data/London/London - 17_lg_splyce.csv', London)
Series('Data/London/London - 18_denial_geng.csv', London)
Series('Data/London/London - 19_faze_nv.csv', London)
Series('Data/London/London - 20_eu_eg.csv', London)
Series('Data/London/London - 21_e6_rec.csv', London)
Series('Data/London/London - 22_heretics_mid.csv', London)
Series('Data/London/London - 23_100t_og.csv', London)
Series('Data/London/London - 24_elevate_uyu.csv', London)
Series('Data/London/London - 25_denial_mid.csv', London)
Series('Data/London/London - 26_eg_rec.csv', London)
Series('Data/London/London - 27_geng_uyu.csv', London)
Series('Data/London/London - 28_100t_eu.csv', London)
Series('Data/London/London - 29_heretics_splyce.csv', London)
Series('Data/London/London - 30_faze_og.csv', London)
Series('Data/London/London - 31_e6_nv.csv', London)
Series('Data/London/London - 32_elevate_lg.csv', London)
Series('Data/London/London - 33_eu_mid.csv', London)
Series('Data/London/London - 34_rec_uyu.csv', London)
Series('Data/London/London - 35_faze_lg.csv', London)
Series('Data/London/London - 36_splyce_nv.csv', London)
Series('Data/London/London - 37_eu_rec.csv', London)
Series('Data/London/London - 38_100t_geng.csv', London)
Series('Data/London/London - 39_lg_nv.csv', London)
Series('Data/London/London - 40_heretics_og.csv', London)
Series('Data/London/London - 41_eu_heretics.csv', London)
Series('Data/London/London - 42_geng_nv.csv', London)
Series('Data/London/London - 43_eu_nv.csv', London)
Series('Data/London/London - 44_100t_og.csv', London)
Series('Data/London/London - 45_eu_og.csv', London)
Series('Data/London/London - 46_100t_eu.csv', London)


#### Pro League Week 7 - Week 10 ####
